name: CI/CD Pipeline

on:
    push:
        branches:
            - "v*.*.*" # Captures les branches avec le format v2.0.0

jobs:
    version-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Versioning
              run: echo "Versioning Step"

    build-and-push:
        runs-on: ubuntu-latest
        needs: version-pipeline
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t projectcicd/frontend:${{ github.ref }} .
                  docker push projectcicd/frontend:${{ github.ref }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t projectcicd/order-service:${{ github.ref }} .
                  docker push projectcicd/order-service:${{ github.ref }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t projectcicd/user-service:${{ github.ref }} .
                  docker push projectcicd/user-service:${{ github.ref }}
